### ISSUE TITLE
cBLUE v.2.2.1 | Exception

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/cBLUE.github.io#38]
### cBLUE v.2.2.1

Getting the following exception when trying to process the TPU

**Loading trajectory files...
100% (12 of 12) |################################################################| Elapsed Time: 0:07:34 Time:  0:07:34
Calculating TPU (multi-processing)...
  0%|                                                                                         | 0/2827 [00:00<?, ?it/s]Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jamie.Kum\.conda\envs\cBLUE\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "CBlueApp.py", line 472, in <lambda>
    b1 = ttk.Button(wseh, text='Ok', command=lambda: self.continue_with_tpu_calc(wseh, float(wseh_value.get())))
  File "CBlueApp.py", line 453, in continue_with_tpu_calc
    self.begin_tpu_calc()
  File "CBlueApp.py", line 552, in begin_tpu_calc
    p = tpu.run_tpu_multiprocess(num_las, sbet_las_tiles_generator())
  File "E:\004327912_data\python_rsd\cBLUE\cBLUE-2.2.1-rc1\Tpu.py", line 354, in run_tpu_multiprocess
    for _ in tqdm(p.imap(self.calc_tpu, sbet_las_generator), total=num_las, ascii=True):
  File "C:\Users\Jamie.Kum\.conda\envs\cBLUE\lib\site-packages\tqdm\std.py", line 1107, in __iter__
    for obj in iterable:
  File "C:\Users\Jamie.Kum\.conda\envs\cBLUE\lib\site-packages\multiprocess\pool.py", line 748, in next
    raise value
AttributeError: 'WindowsPath' object has no attribute 'split'**

**Comment by forkozi** [comment]
this was due to an oversight on my part; i deleted the small chunk of offending troubleshooting code
